# Generated by Django 4.2.28 on 2026-02-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='lesson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='type',
            field=models.CharField(default='strategy', max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='videoUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='bookCover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='readTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
