# Generated by Django 4.2.28 on 2026-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=255)),
                ('lesson', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('directions', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('url', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exclusive_materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
