# Generated by Django 4.2.28 on 2026-02-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivematerial',
            name='size',
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='bookCover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='extraLinks',
            field=models.TextField(blank=True, help_text='Comma separated URLs', null=True),
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exclusivematerial',
            name='videoUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='lesson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='type',
            field=models.CharField(default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exclusivematerial',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
