# Generated by Django 4.2.28 on 2026-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0002_fileitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('exclusive', 'Exclusive'), ('strategy', 'Strategy'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
