# Generated by Django 4.2.28 on 2026-03-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0003_fileitem_category_fileitem_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('exclusive', 'Exclusive'), ('strategy', 'Strategy'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
