# Generated by Django 4.2.28 on 2026-03-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0004_fileitem_description_fileitem_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
